---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: Project name
  config:
    required: true
  description: Short title for your project.
- name: location
  type: text
  config:
    required: false
  label: Location
- type: textarea
  name: description
  label: Description
  description: A description of the project.
  config:
    required: false
- type: file
  name: banner_image
  label: Banner image
  description: This will display on the cover page and Projects page
- name: images
  type: field_group_list
  fields:
  - name: image
    type: file
    config:
      maxSize: 250
    label: Image
  - name: title
    type: text
    config:
      required: false
    label: Title
    description: This will not display, but is something you should fill out.
  - name: caption
    type: text
    config:
      required: false
    label: Caption
  config:
    min: 
    max: 
    labelField: title
  label: images
- type: text
  name: layout
  label: layout
  hidden: true
  default: project
pages:
- _projects/gregory-ii.md
- _projects/gregory-i.md
