---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: Project name
  config:
    required: true
  description: Short title for your project.
- type: textarea
  name: description
  label: Description
  description: A description of the project.
  config:
    required: true
- type: file
  name: banner_image
  label: Banner image
  description: This will display on the cover page and Projects page
- type: field_group_list
  label: Images
  name: images
  fields:
  - type: file
    name: before
    label: Image
  - type: text
    name: caption
    label: Caption
  - type: file
    name: after
    label: Image
  - type: text
    name: caption
    label: Caption
- type: text
  name: layout
  label: layout
  hidden: true
  default: project
pages:
- _projects/gregory-1.md
- _projects/anything-ave.md
- _projects/montecello.md
