---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: Project name
  config:
    required: true
  description: Short title for your project.
- name: location
  type: text
  config:
    required: false
  label: Location
- type: textarea
  name: description
  label: Description
  description: A description of the project.
  config:
    required: false
- type: file
  name: banner_image
  label: Banner image
  description: This will display on the cover page and Projects page
- type: field_group_list
  label: Images
  name: images
  fields:
  - type: file
    name: before
    label: Image
- type: text
  name: layout
  label: layout
  hidden: true
  default: project
- name: project_images
  type: image_gallery
  config: {}
  label: Project images
pages:
- _projects/gregory-2.md
